### ISSUE TITLE
Errors following setup instructions

### ISSUE THREAD

**Issue by iamjaylee** [victorlcampos/gen_guardian#1]
Created a brand new Phoenix app and getting a lot of errors. When I try to run ecto.migrate, looks like nothing is working.

warning: behaviour Guardian.Serializer undefined
undefined function Guardian.Plug.LoadResource.init
Slacker.Router.Helpers is not loaded and could not be found

Generator is using Phoenixcast application name.

**Comment by victorlcampos** [comment]
hi @echojaybird, thx for test gen guardian.
I did some changes.  Could you test again?

Now I follow readme step by step and don't get this errors

**Comment by iamjaylee** [comment]
Fantastic! Works now @victorlcampos. Thanks for putting this together.

**Comment by victorlcampos** [comment]
@echojaybird, welcome. =)
